apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      com.docker.service.id: sugar9-cron
      com.docker.service.name: cron
      com.docker.stack.namespace: sugar9
    name: cron
    namespace: default
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      protocol: TCP
      targetPort: 55555
    selector:
      com.docker.service.id: sugar9-cron
      com.docker.service.name: cron
      com.docker.stack.namespace: sugar9
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      com.docker.service.id: sugar9-db
      com.docker.service.name: db
      com.docker.stack.namespace: sugar9
    name: db
    namespace: default
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      protocol: TCP
      targetPort: 55555
    selector:
      com.docker.service.id: sugar9-db
      com.docker.service.name: db
      com.docker.stack.namespace: sugar9
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      com.docker.service.id: sugar9-db
      com.docker.service.name: db
      com.docker.stack.namespace: sugar9
    name: db-published
    namespace: default
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - name: 3306-tcp
      nodePort: 31068
      port: 3306
      protocol: TCP
      targetPort: 3306
    - name: 33060-tcp
      nodePort: 31089
      port: 33060
      protocol: TCP
      targetPort: 33060
    selector:
      com.docker.service.id: sugar9-db
      com.docker.service.name: db
      com.docker.stack.namespace: sugar9
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - hostname: localhost
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      com.docker.service.id: sugar9-elastic
      com.docker.service.name: elastic
      com.docker.stack.namespace: sugar9
    name: elastic
    namespace: default
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      protocol: TCP
      targetPort: 55555
    selector:
      com.docker.service.id: sugar9-elastic
      com.docker.service.name: elastic
      com.docker.stack.namespace: sugar9
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      com.docker.service.id: sugar9-elastic
      com.docker.service.name: elastic
      com.docker.stack.namespace: sugar9
    name: elastic-published
    namespace: default
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - name: 9200-tcp
      nodePort: 31472
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: 9300-tcp
      nodePort: 32005
      port: 9300
      protocol: TCP
      targetPort: 9300
    selector:
      com.docker.service.id: sugar9-elastic
      com.docker.service.name: elastic
      com.docker.stack.namespace: sugar9
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - hostname: localhost
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      com.docker.service.id: sugar9-web
      com.docker.service.name: web
      com.docker.stack.namespace: sugar9
    name: web
    namespace: default
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 55555
      protocol: TCP
      targetPort: 55555
    selector:
      com.docker.service.id: sugar9-web
      com.docker.service.name: web
      com.docker.stack.namespace: sugar9
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      com.docker.service.id: sugar9-web
      com.docker.service.name: web
      com.docker.stack.namespace: sugar9
    name: web-published
    namespace: default
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - name: 8080-tcp
      nodePort: 30189
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      com.docker.service.id: sugar9-web
      com.docker.service.name: web
      com.docker.stack.namespace: sugar9
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - hostname: localhost
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
